"""Initial migration.

Revision ID: ace11501e3ae
Revises: 
Create Date: 2023-07-21 17:35:55.815115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace11501e3ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('git_hub_id', sa.String(length=32), nullable=False),
    sa.Column('current_question_id', sa.Integer(), nullable=True),
    sa.Column('quiz_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates')),
    sa.UniqueConstraint('email', name=op.f('uq_candidates_email')),
    sa.UniqueConstraint('username', name=op.f('uq_candidates_username'))
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_uuid'), ['uuid'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('correct_answer_mark', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_table('superusers',
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('reset_password_uid', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_superusers')),
    sa.UniqueConstraint('email', name=op.f('uq_superusers_email')),
    sa.UniqueConstraint('username', name=op.f('uq_superusers_username'))
    )
    with op.batch_alter_table('superusers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_superusers_uuid'), ['uuid'], unique=False)

    op.create_table('candidates_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_path', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['candidates.id'], name=op.f('fk_candidates_resumes_user_id_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates_resumes'))
    )
    op.create_table('variant_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=128), nullable=False),
    sa.Column('answer_mark', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_variant_answers_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variant_answers'))
    )
    op.create_table('candidate_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['variant_answers.id'], name=op.f('fk_candidate_answers_answer_id_variant_answers')),
    sa.ForeignKeyConstraint(['user_id'], ['candidates.id'], name=op.f('fk_candidate_answers_user_id_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_answers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_answers')
    op.drop_table('variant_answers')
    op.drop_table('candidates_resumes')
    with op.batch_alter_table('superusers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_superusers_uuid'))

    op.drop_table('superusers')
    op.drop_table('questions')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_uuid'))

    op.drop_table('candidates')
    # ### end Alembic commands ###
